#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
TOTAL_MINUTES=68

# This project keeps local values in .env.local, not .env.
ENV_FILE=".env.local"

# gcloud ships as gcloud.cmd on Windows; resolve it once so Git Bash works.
GC="gcloud"
command -v gcloud >/dev/null 2>&1 || GC="gcloud.cmd"

REGION="us-central1"
INSTANCE="callzie-db"
DBNAME="callzie"
DBUSER="callzie_app"
SERVICE="callzie"
REPO="callzie"

banner "Callzie — infrastructure setup"

# ── 1. Retell webhook key + internal secret ───────────────────────────────
stage "Retell webhook key, and the internal secret" 4
say "Your .env.local has two DIFFERENT Retell keys:"
say "  RETELL_API_KEY        used to call the Retell API"
say "  RETELL_WEBHOOK_SECRET used to verify incoming webhook signatures"
printf '\n'
warn "Retell has no separate webhook secret. It signs with whichever API key"
warn "you designated as the webhook key. If RETELL_WEBHOOK_SECRET is not that"
warn "exact key, every webhook fails verification as a silent 401."
printf '\n'
open_url "https://dashboard.retellai.com/"
step "Find the API keys section of the dashboard."
step "Confirm which key is marked as the webhook key ('Set as Webhook Key')."
step "Only one key can hold that designation at a time."
printf '\n'
if confirm "Is RETELL_WEBHOOK_SECRET in .env.local that exact key?"; then
  say "Good — leaving it as is."
else
  ask_secret RETELL_WEBHOOK_SECRET "Paste the key that IS marked as the webhook key:"
  write_env RETELL_WEBHOOK_SECRET "$RETELL_WEBHOOK_SECRET"
fi

printf '\n'
say "Now the internal secret. It authenticates the Agent's Tool calls and the"
say "extraction endpoint. No provider issues it — we generate it here."
if [[ -n "$(_existing INTERNAL_SECRET || true)" ]]; then
  note "INTERNAL_SECRET already set — keeping it."
else
  if command -v openssl >/dev/null 2>&1; then
    INTERNAL_SECRET=$(openssl rand -hex 32)
  else
    INTERNAL_SECRET=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
  fi
  write_env INTERNAL_SECRET "$INTERNAL_SECRET"
fi

printf '\n'
say "And the token encryption key. It encrypts the Google refresh token before"
say "it is stored (ADR-0009), so a leaked DATABASE_URL does not hand over a"
say "Business's calendar. Generated here too — no provider issues it."
note "Base64, not hex: this one is a 32-byte AES-256 key that gets decoded, not"
note "a random string that gets compared."
if [[ -n "$(_existing TOKEN_ENCRYPTION_KEY || true)" ]]; then
  note "TOKEN_ENCRYPTION_KEY already set — keeping it."
  warn "Never replace it once tokens exist: every stored token becomes"
  warn "undecryptable and every Business must reconnect Google."
else
  if command -v openssl >/dev/null 2>&1; then
    TOKEN_ENCRYPTION_KEY=$(openssl rand -base64 32)
  else
    TOKEN_ENCRYPTION_KEY=$(head -c 32 /dev/urandom | base64 | tr -d '\n')
  fi
  write_env TOKEN_ENCRYPTION_KEY "$TOKEN_ENCRYPTION_KEY"
fi

printf '\n'
say "One more generated value: the Server Action encryption key. Next salts"
say "every Server Action's id with it while building, so every build has to use"
say "the same one — otherwise each deploy renames every action and anyone with"
say "an open tab starts getting errors. See ADR-0008."
if [[ -n "$(_existing NEXT_SERVER_ACTIONS_ENCRYPTION_KEY || true)" ]]; then
  note "NEXT_SERVER_ACTIONS_ENCRYPTION_KEY already set — keeping it."
  note "Generating a fresh one here is exactly the thing to avoid."
else
  if command -v openssl >/dev/null 2>&1; then
    SERVER_ACTIONS_KEY=$(openssl rand -base64 32)
  else
    SERVER_ACTIONS_KEY=$(head -c 32 /dev/urandom | base64 | tr -d '\n')
  fi
  write_env NEXT_SERVER_ACTIONS_ENCRYPTION_KEY "$SERVER_ACTIONS_KEY"
fi

printf '\n'
warn "While you are in the Retell dashboard: submit KYC now if you have not."
warn "It gates outbound calling and number purchase, one path is manual review"
warn "with no published turnaround, and nothing else here depends on it."
pause "Press Enter when KYC is submitted (or you've decided to skip phone calls)."

# ── 2. gcloud CLI ─────────────────────────────────────────────────────────
stage "Install and authenticate the gcloud CLI" 12
if command -v gcloud >/dev/null 2>&1 || command -v gcloud.cmd >/dev/null 2>&1; then
  say "gcloud is already installed."
else
  open_url "https://cloud.google.com/sdk/docs/install"
  step "Download and run the Windows installer for the Google Cloud CLI."
  step "Leave 'Run gcloud init' ticked at the end."
  warn "After installing you MUST close and reopen this terminal, then re-run"
  warn "this wizard — a new PATH is not visible to an already-running shell."
  pause "Press Enter once installed (then re-run if gcloud is still missing)."
  command -v gcloud >/dev/null 2>&1 || command -v gcloud.cmd >/dev/null 2>&1 || {
    warn "gcloud still not on PATH. Reopen the terminal and re-run this wizard."
    exit 1
  }
fi

say "Two logins are needed: one for the CLI, one for local libraries."
"$GC" auth login
"$GC" auth application-default login

# ── 3. Project, billing, APIs ─────────────────────────────────────────────
stage "GCP project, billing and APIs" 8
say "Creating a dedicated project keeps Callzie's spend and resources isolated."
ask GCP_PROJECT_ID "Project id to use or create (lowercase, e.g. callzie-app-2026):"

if "$GC" projects describe "$GCP_PROJECT_ID" >/dev/null 2>&1; then
  say "Project already exists — using it."
else
  confirm "Create project $GCP_PROJECT_ID?" || { warn "Aborted."; exit 1; }
  "$GC" projects create "$GCP_PROJECT_ID" --name="Callzie"
fi
"$GC" config set project "$GCP_PROJECT_ID"
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
write_env GCP_REGION "$REGION"

printf '\n'
say "Linking the billing account holding your \$300 trial credit."
warn "Nothing here is free: Cloud SQL has no free tier (ADR-0001 accepted"
warn "~\$9.37/month), and the trial credit expires after 90 days, deleting the"
warn "project and the live URL with it."
"$GC" billing accounts list
ask GCP_BILLING_ACCOUNT "Paste the ACCOUNT_ID of your billing account:"
"$GC" billing projects link "$GCP_PROJECT_ID" --billing-account="$GCP_BILLING_ACCOUNT"

printf '\n'
say "Enabling the five APIs this project needs."
"$GC" services enable \
  run.googleapis.com \
  sqladmin.googleapis.com \
  secretmanager.googleapis.com \
  cloudbuild.googleapis.com \
  artifactregistry.googleapis.com

# ── 4. Cloud SQL ──────────────────────────────────────────────────────────
stage "Cloud SQL instance, database and user" 15
warn "This creates a billable resource and takes 5-10 minutes to provision."
confirm "Create the Cloud SQL instance now?" || { warn "Aborted."; exit 1; }

if "$GC" sql instances describe "$INSTANCE" >/dev/null 2>&1; then
  say "Instance $INSTANCE already exists — skipping creation."
else
  "$GC" sql instances create "$INSTANCE" \
    --database-version=POSTGRES_16 \
    --tier=db-f1-micro \
    --region="$REGION" \
    --storage-size=10GB \
    --storage-type=HDD \
    --no-backup || {
      warn "Creation failed. If the tier was rejected, run:"
      warn "  $GC sql tiers list"
      warn "and re-run this wizard with a tier from that list."
      exit 1
    }
fi

"$GC" sql databases describe "$DBNAME" --instance="$INSTANCE" >/dev/null 2>&1 \
  || "$GC" sql databases create "$DBNAME" --instance="$INSTANCE"

printf '\n'
say "Creating the application database user."
note "Alphanumeric password only — it goes inside a URL, and punctuation there"
note "needs percent-encoding, which is a silent source of connection failures."
if command -v openssl >/dev/null 2>&1; then
  DBPASS=$(openssl rand -hex 24)
else
  DBPASS=$(head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')
fi
"$GC" sql users create "$DBUSER" --instance="$INSTANCE" --password="$DBPASS" 2>/dev/null \
  || "$GC" sql users set-password "$DBUSER" --instance="$INSTANCE" --password="$DBPASS"

CONN=$("$GC" sql instances describe "$INSTANCE" --format='value(connectionName)')
say "Connection name: $CONN"
write_env CLOUDSQL_CONNECTION_NAME "$CONN"

# Local URL goes through the Auth Proxy; Cloud Run uses the unix socket.
write_env DATABASE_URL "postgresql://${DBUSER}:${DBPASS}@127.0.0.1:5432/${DBNAME}"
DATABASE_URL_CLOUD="postgresql://${DBUSER}:${DBPASS}@/${DBNAME}?host=/cloudsql/${CONN}"

# ── 5. Migrations ─────────────────────────────────────────────────────────
stage "Apply migrations through the Auth Proxy" 6
say "The proxy gives your machine a local port that tunnels to Cloud SQL, so"
say "no public IP allowlist is ever needed (ADR-0001)."
printf '\n'
step "Open a SECOND terminal in this folder and run:"
note "    ./bin/cloud-sql-proxy.exe $CONN --port 5432"
step "Leave it running."
pause "Press Enter once the proxy says it is ready."

npm run db:migrate
say "Both migrations applied — including the hand-written no-overlap constraint."

# ── 6. Secret Manager ─────────────────────────────────────────────────────
stage "Store runtime secrets in Secret Manager" 6
say "Server-only secrets never enter the image; Cloud Run injects them at boot."

put_secret() { # put_secret <secret-name> <value>
  if "$GC" secrets describe "$1" >/dev/null 2>&1; then
    printf '%s' "$2" | "$GC" secrets versions add "$1" --data-file=- >/dev/null
  else
    printf '%s' "$2" | "$GC" secrets create "$1" --data-file=- --replication-policy=automatic >/dev/null
  fi
  printf '  %s✓ stored%s %s\n' "$GREEN" "$RESET" "$1"
}

put_secret callzie-database-url        "$DATABASE_URL_CLOUD"
put_secret callzie-clerk-secret-key    "$(_existing CLERK_SECRET_KEY)"
put_secret callzie-retell-api-key      "$(_existing RETELL_API_KEY)"
put_secret callzie-retell-webhook-secret "$(_existing RETELL_WEBHOOK_SECRET)"
put_secret callzie-anthropic-api-key   "$(_existing ANTHROPIC_API_KEY)"
put_secret callzie-internal-secret     "$(_existing INTERNAL_SECRET)"
# Runtime-only, like every secret above: it is read when a Google token is
# encrypted or decrypted, never at build time. It therefore stays out of
# cloudbuild.yaml and out of the image — a key baked into a layer is a key that
# ships to anyone who can pull it.
put_secret callzie-token-encryption-key "$(_existing TOKEN_ENCRYPTION_KEY)"
put_secret callzie-server-actions-encryption-key "$(_existing NEXT_SERVER_ACTIONS_ENCRYPTION_KEY)"

# The Google Calendar handshake (issue #20, ADR-0004). OPTIONAL, and stored only
# when they are already in .env.local -- a deployment with no Google integration
# is correctly configured, not degraded, so an absent pair is not a failure.
#
# The client id is not really a secret; it is public on the consent screen. It
# lives here anyway so both halves of the handshake are configured the same way
# and neither can be left behind when the other is rotated.
if [[ -n "$(_existing GOOGLE_CLIENT_ID || true)" && -n "$(_existing GOOGLE_CLIENT_SECRET || true)" ]]; then
  put_secret callzie-google-client-id     "$(_existing GOOGLE_CLIENT_ID)"
  put_secret callzie-google-client-secret "$(_existing GOOGLE_CLIENT_SECRET)"
  GOOGLE_SECRETS="callzie-google-client-id callzie-google-client-secret"
  GOOGLE_RUN_SECRETS=",GOOGLE_CLIENT_ID=callzie-google-client-id:latest,GOOGLE_CLIENT_SECRET=callzie-google-client-secret:latest"
else
  note "GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET not set -- skipping. Google Calendar stays off (ADR-0004)."
  GOOGLE_SECRETS=""
  GOOGLE_RUN_SECRETS=""
fi

printf '\n'
say "Granting the Cloud Run runtime service account read access."
PROJNUM=$("$GC" projects describe "$GCP_PROJECT_ID" --format='value(projectNumber)')
RUNTIME_SA="${PROJNUM}-compute@developer.gserviceaccount.com"
for s in callzie-database-url callzie-clerk-secret-key callzie-retell-api-key \
         callzie-retell-webhook-secret callzie-anthropic-api-key callzie-internal-secret \
         callzie-token-encryption-key $GOOGLE_SECRETS; do
  "$GC" secrets add-iam-policy-binding "$s" \
    --member="serviceAccount:${RUNTIME_SA}" \
    --role=roles/secretmanager.secretAccessor >/dev/null
done
say "Access granted to $RUNTIME_SA"

printf '\n'
say "The Server Action key is read by Cloud BUILD, not Cloud Run — it is baked"
say "into the image rather than injected at boot, so it needs a different grant"
say "and is deliberately absent from the --set-secrets list below."
note "Which account a build runs as depends on a project setting: the legacy"
note "Cloud Build account, or the Compute default. Granting both is idempotent"
note "and costs nothing when one of them goes unused."
for sa in "${PROJNUM}@cloudbuild.gserviceaccount.com" "${RUNTIME_SA}"; do
  "$GC" secrets add-iam-policy-binding callzie-server-actions-encryption-key \
    --member="serviceAccount:${sa}" \
    --role=roles/secretmanager.secretAccessor >/dev/null 2>&1 \
    || warn "could not grant $sa — grant it by hand before the first build"
done

# ── 7. Build and deploy ───────────────────────────────────────────────────
stage "Build the image and deploy to Cloud Run" 12
say "Cloud Build builds your Dockerfile remotely — no local Docker needed."
note "The Clerk publishable key is a build arg because Next inlines NEXT_PUBLIC_*"
note "at build time. So is the Server Action encryption key, which Next bakes"
note "into its own build output — Cloud Build pulls that one from Secret Manager"
note "itself, so it is not passed here. Every other server secret stays out of"
note "the image and arrives at runtime."

"$GC" artifacts repositories describe "$REPO" --location="$REGION" >/dev/null 2>&1 \
  || "$GC" artifacts repositories create "$REPO" \
       --repository-format=docker --location="$REGION" \
       --description="Callzie container images"

IMAGE="${REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${REPO}/${SERVICE}:latest"
CLERK_PK=$(_existing NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY)

"$GC" builds submit --config cloudbuild.yaml \
  --substitutions="_IMAGE=${IMAGE},_CLERK_PUBLISHABLE_KEY=${CLERK_PK}"

printf '\n'
say "Deploying. --no-cpu-throttling keeps CPU allocated after the response is"
say "sent, which is what SPEC.md §13 item 7 flags as the open question for"
say "post-response extraction work on Cloud Run."
"$GC" run deploy "$SERVICE" \
  --image="$IMAGE" \
  --region="$REGION" \
  --platform=managed \
  --allow-unauthenticated \
  --no-cpu-throttling \
  --add-cloudsql-instances="$CONN" \
  --set-env-vars="NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${CLERK_PK}" \
  --set-secrets="DATABASE_URL=callzie-database-url:latest,CLERK_SECRET_KEY=callzie-clerk-secret-key:latest,RETELL_API_KEY=callzie-retell-api-key:latest,RETELL_WEBHOOK_SECRET=callzie-retell-webhook-secret:latest,ANTHROPIC_API_KEY=callzie-anthropic-api-key:latest,INTERNAL_SECRET=callzie-internal-secret:latest,TOKEN_ENCRYPTION_KEY=callzie-token-encryption-key:latest${GOOGLE_RUN_SECRETS}"

# ── 8. Wire APP_URL back ──────────────────────────────────────────────────
stage "Capture the live URL and wire it back" 5
SERVICE_URL=$("$GC" run services describe "$SERVICE" --region="$REGION" --format='value(status.url)')
say "Live URL: $SERVICE_URL"
write_env APP_URL "$SERVICE_URL"

say "Redeploying so the running service knows its own public URL."
"$GC" run services update "$SERVICE" --region="$REGION" \
  --update-env-vars="APP_URL=${SERVICE_URL}"

printf '\n'
open_url "https://dashboard.clerk.com/"
step "Open your Callzie application, find its domain / allowed origins setting."
step "Add: $SERVICE_URL"
note "Without this, sign-in works locally but fails on the deployed URL."
pause "Press Enter once added."

printf '\n'
open_url "$SERVICE_URL"
step "Confirm the deployed app loads."

SKIPPED+=("Retell Agents — run 'npm run create-agents' now that APP_URL is set. It provisions all four and records their ids in the retell_agents table; no new env var or secret is needed.")
SKIPPED+=("RETELL_FROM_NUMBER — needs Retell KYC to clear, then buy a \$2 US number (issue #19)")
SKIPPED+=("Google Calendar — optional (ADR-0004). If GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET are in .env.local this script has already stored and wired them; if not, add them and re-run. Register ${SERVICE_URL}/api/google/callback as an authorised redirect URI, and add yourself as a test user while the app is in Testing.")

finish
